### ISSUE TITLE
Triggers a Julia assertion on nightly

### ISSUE THREAD

**Issue by tkelman** [KristofferC/Tensors.jl#62] opened 2017-04-29 09:42 UTC
would be good to reduce and report this upstream, if it hasn't been
```
cat Make.user && JULIA_PKGDIR=$PWD/../jlpkgtmp ./julia -e 'versioninfo(); Pkg.init(); Pkg.add("Tensors"); Pkg.test("Tensors")'
override LLVM_ASSERTIONS = 1
override MARCH = x86-64
CMAKE = /home/tkelman2/Julia/julia-0.6/deps/scratch/cmake-3.7.1-Linux-x86_64/bin/cmake
Julia Version 0.6.0-pre.beta.415
Commit 19b3f50* (2017-04-29 09:02 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
INFO: Initializing package repository /home/tkelman2/Julia/jlpkgtmp/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of Calculus from https://github.com/johnmyleswhite/Calculus.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of DiffBase from https://github.com/JuliaDiff/DiffBase.jl.git
INFO: Cloning cache of ForwardDiff from https://github.com/JuliaDiff/ForwardDiff.jl.git
INFO: Cloning cache of NaNMath from https://github.com/mlubin/NaNMath.jl.git
INFO: Cloning cache of SIMD from https://github.com/eschnett/SIMD.jl.git
INFO: Cloning cache of SpecialFunctions from https://github.com/JuliaMath/SpecialFunctions.jl.git
INFO: Cloning cache of Tensors from https://github.com/KristofferC/Tensors.jl.git
INFO: Installing Calculus v0.2.2
INFO: Installing Compat v0.24.0
INFO: Installing DiffBase v0.1.0
INFO: Installing ForwardDiff v0.4.2
INFO: Installing NaNMath v0.2.4
INFO: Installing SIMD v0.2.0
INFO: Installing SpecialFunctions v0.1.1
INFO: Installing Tensors v0.6.1
INFO: Package database updated
INFO: Computing test dependencies for Tensors...
INFO: Cloning cache of Crayons from https://github.com/KristofferC/Crayons.jl.git
INFO: Cloning cache of DocStringExtensions from https://github.com/JuliaDocs/DocStringExtensions.jl.git
INFO: Cloning cache of Documenter from https://github.com/JuliaDocs/Documenter.jl.git
INFO: Cloning cache of TimerOutputs from https://github.com/KristofferC/TimerOutputs.jl.git
INFO: Installing Crayons v0.2.0
INFO: Installing DocStringExtensions v0.3.3
INFO: Installing Documenter v0.10.0
INFO: Installing TimerOutputs v0.2.6
INFO: Testing Tensors
Test Summary: | Pass  Total
constructors  |  333    333
Test Summary: | Pass  Total
diagm, one    |  762    762
Test Summary: | Pass  Total
base vectors  |   45     45
julia: /home/tkelman2/Julia/julia-0.6/src/cgutils.cpp:527: llvm::Type* julia_struct_to_llvm(jl_value_t*, jl_unionall_t*, bool*): Assertion `llvm_alignment == julia_alignment' failed.

signal (6): Aborted
while loading /home/tkelman2/Julia/jlpkgtmp/v0.6/Tensors/test/test_misc.jl, in expression starting on line 123
raise at /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56
abort at /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:89
__assert_fail_base at /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92
__assert_fail at /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:101
julia_struct_to_llvm at /home/tkelman2/Julia/julia-0.6/src/cgutils.cpp:527
julia_type_to_llvm at /home/tkelman2/Julia/julia-0.6/src/cgutils.cpp:388
julia_struct_to_llvm at /home/tkelman2/Julia/julia-0.6/src/cgutils.cpp:484
julia_type_to_llvm at /home/tkelman2/Julia/julia-0.6/src/cgutils.cpp:388
mark_julia_type at /home/tkelman2/Julia/julia-0.6/src/codegen.cpp:774
emit_function at /home/tkelman2/Julia/julia-0.6/src/codegen.cpp:5244
jl_compile_linfo at /home/tkelman2/Julia/julia-0.6/src/codegen.cpp:1256
jl_compile_for_dispatch at /home/tkelman2/Julia/julia-0.6/src/gf.c:1672
jl_compile_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:305 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:352 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
jl_apply at /home/tkelman2/Julia/julia-0.6/src/julia.h:1422 [inlined]
jl_f__apply at /home/tkelman2/Julia/julia-0.6/src/builtins.c:426
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
do_call at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:75
eval at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:242
eval_body at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:546
eval_body at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:592
jl_interpret_toplevel_thunk at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:695
jl_toplevel_eval_flex at /home/tkelman2/Julia/julia-0.6/src/toplevel.c:590 [inlined]
jl_toplevel_eval at /home/tkelman2/Julia/julia-0.6/src/toplevel.c:598
jl_toplevel_eval_in at /home/tkelman2/Julia/julia-0.6/src/builtins.c:496
macro expansion at /home/tkelman2/Julia/jlpkgtmp/v0.6/Tensors/test/test_misc.jl:119 [inlined]
macro expansion at ./test.jl:853 [inlined]
macro expansion at /home/tkelman2/Julia/jlpkgtmp/v0.6/Tensors/test/runtests.jl:9 [inlined]
macro expansion at /home/tkelman2/Julia/jlpkgtmp/v0.6/TimerOutputs/src/TimerOutput.jl:128 [inlined]
macro expansion at /home/tkelman2/Julia/jlpkgtmp/v0.6/Tensors/test/runtests.jl:8 [inlined]
anonymous at ./<missing> (unknown line)
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_toplevel_eval_flex at /home/tkelman2/Julia/julia-0.6/src/toplevel.c:587
jl_parse_eval_all at /home/tkelman2/Julia/julia-0.6/src/ast.c:873
jl_load at /home/tkelman2/Julia/julia-0.6/src/toplevel.c:614
include_from_node1 at ./loading.jl:539
unknown function (ip: 0x7fe660555852)
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
include at ./sysimg.jl:14
unknown function (ip: 0x7fe67c5e944b)
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
do_call at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:75
eval at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/tkelman2/Julia/julia-0.6/src/interpreter.c:34
jl_toplevel_eval_flex at /home/tkelman2/Julia/julia-0.6/src/toplevel.c:575
jl_parse_eval_all at /home/tkelman2/Julia/julia-0.6/src/ast.c:873
jl_load at /home/tkelman2/Julia/julia-0.6/src/toplevel.c:614
include_from_node1 at ./loading.jl:539
unknown function (ip: 0x7fe67c7544eb)
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
include at ./sysimg.jl:14
unknown function (ip: 0x7fe67c5e944b)
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
process_options at ./client.jl:305
_start at ./client.jl:371
unknown function (ip: 0x7fe67c75fc48)
jl_call_fptr_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/tkelman2/Julia/julia-0.6/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/tkelman2/Julia/julia-0.6/src/gf.c:1930
jl_apply at /home/tkelman2/Julia/julia-0.6/ui/../src/julia.h:1422 [inlined]
true_main at /home/tkelman2/Julia/julia-0.6/ui/repl.c:127
main at /home/tkelman2/Julia/julia-0.6/ui/repl.c:264
__libc_start_main at /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:287
unknown function (ip: 0x4015fa)
Allocations: 16955857 (Pool: 16951856; Big: 4001); GC: 37
====================================[ ERROR: Tensors ]====================================

failed process: Process(`/home/tkelman2/Julia/julia-0.6/usr/bin/julia -Cx86-64 -J/home/tkelman2/Julia/julia-0.6/usr/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/tkelman2/Julia/jlpkgtmp/v0.6/Tensors/test/runtests.jl`, ProcessSignaled(6)) [0]

==========================================================================================
INFO: Removing Crayons v0.2.0
INFO: Removing DocStringExtensions v0.3.3
INFO: Removing Documenter v0.10.0
INFO: Removing TimerOutputs v0.2.6
ERROR: Tensors had test errors
```

also happens on master of the package

**Comment by fredrikekre** [comment] 2017-05-02 12:58
I think it might be https://github.com/JuliaLang/julia/issues/20961

**Comment by KristofferC** [comment] 2017-05-02 13:00
So this is not an LLVM assertion but a Julia runtime assertion?

**Comment by tkelman** [comment] 2017-05-02 13:05
Ah, my mistake, yes. I think something changed in the build configuration so enabling LLVM assertions also enables some or all of the libjulia assertions.

**Comment by fredrikekre** [comment] 2017-05-02 13:07
It's https://github.com/JuliaLang/julia/issues/20961 I am pretty sure. Its only visible for lengths above 32 as I mentioned in that issue.

**Comment by KristofferC** [comment] 2017-05-02 13:13
Why doesn't `Pkg.test()` run with `julia-debug`?

**Comment by tkelman** [comment] 2017-05-02 13:14
it might if you were to run it from julia-debug

**Comment by KristofferC** [comment] 2017-05-02 13:14
I meant by default (on Travis)

**Comment by KristofferC** [comment] 2017-05-02 13:21
Isn't that the whole point though? To have a debug build that does checks that are not possible to efficiently check at runtime and catch more bugs.

**Comment by tkelman** [comment] 2017-05-02 13:28
Not if that would run tests much more slowly and result in CI timeouts, or give different behavior. `julia-debug` isn't all that valuable outside of running in a debugger.

**Comment by KristofferC** [comment] 2017-05-02 13:31
Anyway, I updated https://github.com/JuliaLang/julia/issues/20961#issuecomment-298633856 with a reproducer. I wonder if the assertion is too strict since we have been running the code here quite extensively without problem.

**Comment by KristofferC** [comment] 2017-05-30 07:22
Closed by https://github.com/JuliaLang/julia/pull/21980

**Closed by KristofferC** 2017-05-30 07:22 UTC
